version: '2.1'

services:
  loc:
    image: c-loc
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9001:9001
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js
